# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tkscoot/git/projects/procrop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tkscoot/git/projects/procrop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tkscoot/git/projects/procrop/CMakeFiles /home/tkscoot/git/projects/procrop//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tkscoot/git/projects/procrop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named procrop

# Build rule for target.
procrop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 procrop
.PHONY : procrop

# fast build rule for target.
procrop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/build
.PHONY : procrop/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

source/Application.o: source/Application.cpp.o
.PHONY : source/Application.o

# target to build an object file
source/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Application.cpp.o
.PHONY : source/Application.cpp.o

source/Application.i: source/Application.cpp.i
.PHONY : source/Application.i

# target to preprocess a source file
source/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Application.cpp.i
.PHONY : source/Application.cpp.i

source/Application.s: source/Application.cpp.s
.PHONY : source/Application.s

# target to generate assembly for a file
source/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Application.cpp.s
.PHONY : source/Application.cpp.s

source/Debug.o: source/Debug.cpp.o
.PHONY : source/Debug.o

# target to build an object file
source/Debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Debug.cpp.o
.PHONY : source/Debug.cpp.o

source/Debug.i: source/Debug.cpp.i
.PHONY : source/Debug.i

# target to preprocess a source file
source/Debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Debug.cpp.i
.PHONY : source/Debug.cpp.i

source/Debug.s: source/Debug.cpp.s
.PHONY : source/Debug.s

# target to generate assembly for a file
source/Debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Debug.cpp.s
.PHONY : source/Debug.cpp.s

source/Engine.o: source/Engine.cpp.o
.PHONY : source/Engine.o

# target to build an object file
source/Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Engine.cpp.o
.PHONY : source/Engine.cpp.o

source/Engine.i: source/Engine.cpp.i
.PHONY : source/Engine.i

# target to preprocess a source file
source/Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Engine.cpp.i
.PHONY : source/Engine.cpp.i

source/Engine.s: source/Engine.cpp.s
.PHONY : source/Engine.s

# target to generate assembly for a file
source/Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Engine.cpp.s
.PHONY : source/Engine.cpp.s

source/GameObject.o: source/GameObject.cpp.o
.PHONY : source/GameObject.o

# target to build an object file
source/GameObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/GameObject.cpp.o
.PHONY : source/GameObject.cpp.o

source/GameObject.i: source/GameObject.cpp.i
.PHONY : source/GameObject.i

# target to preprocess a source file
source/GameObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/GameObject.cpp.i
.PHONY : source/GameObject.cpp.i

source/GameObject.s: source/GameObject.cpp.s
.PHONY : source/GameObject.s

# target to generate assembly for a file
source/GameObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/GameObject.cpp.s
.PHONY : source/GameObject.cpp.s

source/GridChunk.o: source/GridChunk.cpp.o
.PHONY : source/GridChunk.o

# target to build an object file
source/GridChunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/GridChunk.cpp.o
.PHONY : source/GridChunk.cpp.o

source/GridChunk.i: source/GridChunk.cpp.i
.PHONY : source/GridChunk.i

# target to preprocess a source file
source/GridChunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/GridChunk.cpp.i
.PHONY : source/GridChunk.cpp.i

source/GridChunk.s: source/GridChunk.cpp.s
.PHONY : source/GridChunk.s

# target to generate assembly for a file
source/GridChunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/GridChunk.cpp.s
.PHONY : source/GridChunk.cpp.s

source/Image.o: source/Image.cpp.o
.PHONY : source/Image.o

# target to build an object file
source/Image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Image.cpp.o
.PHONY : source/Image.cpp.o

source/Image.i: source/Image.cpp.i
.PHONY : source/Image.i

# target to preprocess a source file
source/Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Image.cpp.i
.PHONY : source/Image.cpp.i

source/Image.s: source/Image.cpp.s
.PHONY : source/Image.s

# target to generate assembly for a file
source/Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Image.cpp.s
.PHONY : source/Image.cpp.s

source/Player.o: source/Player.cpp.o
.PHONY : source/Player.o

# target to build an object file
source/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Player.cpp.o
.PHONY : source/Player.cpp.o

source/Player.i: source/Player.cpp.i
.PHONY : source/Player.i

# target to preprocess a source file
source/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Player.cpp.i
.PHONY : source/Player.cpp.i

source/Player.s: source/Player.cpp.s
.PHONY : source/Player.s

# target to generate assembly for a file
source/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/Player.cpp.s
.PHONY : source/Player.cpp.s

source/TextRenderer.o: source/TextRenderer.cpp.o
.PHONY : source/TextRenderer.o

# target to build an object file
source/TextRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/TextRenderer.cpp.o
.PHONY : source/TextRenderer.cpp.o

source/TextRenderer.i: source/TextRenderer.cpp.i
.PHONY : source/TextRenderer.i

# target to preprocess a source file
source/TextRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/TextRenderer.cpp.i
.PHONY : source/TextRenderer.cpp.i

source/TextRenderer.s: source/TextRenderer.cpp.s
.PHONY : source/TextRenderer.s

# target to generate assembly for a file
source/TextRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/TextRenderer.cpp.s
.PHONY : source/TextRenderer.cpp.s

source/TileMap.o: source/TileMap.cpp.o
.PHONY : source/TileMap.o

# target to build an object file
source/TileMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/TileMap.cpp.o
.PHONY : source/TileMap.cpp.o

source/TileMap.i: source/TileMap.cpp.i
.PHONY : source/TileMap.i

# target to preprocess a source file
source/TileMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/TileMap.cpp.i
.PHONY : source/TileMap.cpp.i

source/TileMap.s: source/TileMap.cpp.s
.PHONY : source/TileMap.s

# target to generate assembly for a file
source/TileMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/TileMap.cpp.s
.PHONY : source/TileMap.cpp.s

source/VirtualFileSystem.o: source/VirtualFileSystem.cpp.o
.PHONY : source/VirtualFileSystem.o

# target to build an object file
source/VirtualFileSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/VirtualFileSystem.cpp.o
.PHONY : source/VirtualFileSystem.cpp.o

source/VirtualFileSystem.i: source/VirtualFileSystem.cpp.i
.PHONY : source/VirtualFileSystem.i

# target to preprocess a source file
source/VirtualFileSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/VirtualFileSystem.cpp.i
.PHONY : source/VirtualFileSystem.cpp.i

source/VirtualFileSystem.s: source/VirtualFileSystem.cpp.s
.PHONY : source/VirtualFileSystem.s

# target to generate assembly for a file
source/VirtualFileSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/VirtualFileSystem.cpp.s
.PHONY : source/VirtualFileSystem.cpp.s

source/WorldGrid.o: source/WorldGrid.cpp.o
.PHONY : source/WorldGrid.o

# target to build an object file
source/WorldGrid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/WorldGrid.cpp.o
.PHONY : source/WorldGrid.cpp.o

source/WorldGrid.i: source/WorldGrid.cpp.i
.PHONY : source/WorldGrid.i

# target to preprocess a source file
source/WorldGrid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/WorldGrid.cpp.i
.PHONY : source/WorldGrid.cpp.i

source/WorldGrid.s: source/WorldGrid.cpp.s
.PHONY : source/WorldGrid.s

# target to generate assembly for a file
source/WorldGrid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/WorldGrid.cpp.s
.PHONY : source/WorldGrid.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/procrop.dir/build.make CMakeFiles/procrop.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... procrop"
	@echo "... source/Application.o"
	@echo "... source/Application.i"
	@echo "... source/Application.s"
	@echo "... source/Debug.o"
	@echo "... source/Debug.i"
	@echo "... source/Debug.s"
	@echo "... source/Engine.o"
	@echo "... source/Engine.i"
	@echo "... source/Engine.s"
	@echo "... source/GameObject.o"
	@echo "... source/GameObject.i"
	@echo "... source/GameObject.s"
	@echo "... source/GridChunk.o"
	@echo "... source/GridChunk.i"
	@echo "... source/GridChunk.s"
	@echo "... source/Image.o"
	@echo "... source/Image.i"
	@echo "... source/Image.s"
	@echo "... source/Player.o"
	@echo "... source/Player.i"
	@echo "... source/Player.s"
	@echo "... source/TextRenderer.o"
	@echo "... source/TextRenderer.i"
	@echo "... source/TextRenderer.s"
	@echo "... source/TileMap.o"
	@echo "... source/TileMap.i"
	@echo "... source/TileMap.s"
	@echo "... source/VirtualFileSystem.o"
	@echo "... source/VirtualFileSystem.i"
	@echo "... source/VirtualFileSystem.s"
	@echo "... source/WorldGrid.o"
	@echo "... source/WorldGrid.i"
	@echo "... source/WorldGrid.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

